services:
  postgres:
    image: postgres:15-alpine
    container_name: auth-api-postgres
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: fernandakipper
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fernandakipper -d product"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

